project: team-week-3
dataset: 'tech_stocks_world_events'
key_path: "./cred/team-week-3-2f1d10dceea4.json"

#rg_key_path = "/Users/Ruben/Desktop/google_cred/.cred/team_project_3/team-week-3-2f1d10dceea4.json"